### ISSUE TITLE
Integration with homebrew/homebrew bundle?

### ISSUE THREAD

**Issue by anubhavcodes** [whalebrew/whalebrew#101]
First of all, thanks a lot for this wonderful project. Makes my life easier trying to run awscli without really install these cli on my host system. 

I also heavily rely on homebrew's [bundle](https://github.com/Homebrew/homebrew-bundle) to bootstrap my mac's apps. I have to reinstall apps many times on new machines. 

Is it possible to package whalebrew as a cask and then tap that cask and install apps via whalebrew? This will make it easier for people to also use whalebrew with scripts like brew bundle. 

Or is it already working with brew's bundle?

**Comment by jacobbednarz** [comment]
Hombrew (cask and bundle) support already works. See https://github.com/Homebrew/homebrew-bundle/blob/master/README.md

**Comment by anubhavcodes** [comment]
This is really really good. Thank you. :)
