### ISSUE TITLE
whalebrew search doesn't return any results

### ISSUE THREAD

**Issue by unixorn** [whalebrew/whalebrew#105]
`whalebrew search` doesn't return any results, but I can `whalebrew install` if I know the container name.

```
bash-3.2$ whalebrew search
bash-3.2$ whalebrew search ansible
bash-3.2$ whalebrew install whalebrew/ansible
Unable to find image 'whalebrew/ansible' locally
Using default tag: latest
latest: Pulling from whalebrew/ansible
c9b1b535fdd9: Already exists
394a08e0f610: Pull complete
214a4266a527: Pull complete
21a86fecc2be: Pull complete
Digest: sha256:e38524b06074f0a666ea21c536340577cd6f057c7540d70f7ee7f7a737eade68
Status: Downloaded newer image for whalebrew/ansible:latest
docker.io/whalebrew/ansible:latest
🐳  Installed whalebrew/ansible to /usr/local/bin/ansible
bash-3.2$
```

I'm running 0.23 (installed with homebrew per the readme) and have this happening on both of my Macs, both running Catalina.

**Comment by aidanmelen** [comment]
experiencing the same. Also MacOS Catalina.

**Comment by unixorn** [comment]
I'm running 10.15.6 on both of my machines.

**Comment by tjamet** [comment]
Thanks for raising. I will take a look at it
It might relate to #102

**Comment by tjamet** [comment]
I was having a deeper look, it seems that the problem is related to the fact that #89 has not been released yet.
Let's make a new one

**Comment by tjamet** [comment]
I just released a new version, which should solve the problem. Can you confirm?

**Comment by unixorn** [comment]
That fixed it!

Though whalebrew version still reports 0.23.

I installed with `curl -L "https://github.com/whalebrew/whalebrew/releases/download/0.2.4/whalebrew-$(uname -s)-$(uname -m)" -o /usr/local/bin/whalebrew; chmod +x /usr/local/bin/whalebrew`

**Comment by unixorn** [comment]
Thanks, this is a really cool tool - I'd already started putting some of my more used stuff into containers, but I'm going to go back and make them (at least what you don't already have packaged) whalebrew-compatible.

**Comment by tjamet** [comment]
yes, the release is still a bit flappy, I will try to improve it in future releases
