### ISSUE TITLE
whalebrew search panics when called without arguments

### ISSUE THREAD

**Issue by KevinSjoberg** [whalebrew/whalebrew#118]
On macOS (11.0.1), using whalebrew, version 0.2.5, running `whalebrew search` without any arguments cause a panic. I'd expect the help text for search to be shown instead.

```console
$ whalebrew search
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/whalebrew/whalebrew/cmd.glob..func4(0x1a68600, 0x1aa25b8, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/whalebrew-20201115-55548-14de8lv/cmd/search.go:30 +0x216
github.com/spf13/cobra.(*Command).execute(0x1a68600, 0x1aa25b8, 0x0, 0x0, 0x1a68600, 0x1aa25b8)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20190321000552-67fc4837d267/command.go:762 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x1a683a0, 0x168af85, 0x1, 0x1008200)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20190321000552-67fc4837d267/command.go:850 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20190321000552-67fc4837d267/command.go:800
main.main()
	/private/tmp/whalebrew-20201115-55548-14de8lv/main.go:15 +0x46
```

**Comment by tjamet** [comment]
Thanks for raising. I will take a look soon

**Comment by KevinSjoberg** [comment]
@tjamet no worries. 🙂 I believe the culprit is here https://github.com/whalebrew/whalebrew/blob/2dcc6cd988c0e1f7ea9c1591ad29c4d0d3fc63dd/cmd/search.go#L21. We should have check similar to what we do in https://github.com/whalebrew/whalebrew/blob/2dcc6cd988c0e1f7ea9c1591ad29c4d0d3fc63dd/cmd/install.go#L34-L36.

I wanted to submit a pull request myself, but didn't really understand how to setup everything up. Thought the `Dockerfile` could be used, but I never manage to run it to completion. It stalled on installing go packages.

**Comment by tjamet** [comment]
strange, the project should be buildable with a plain go build, using go 1.15
Though, I just sent a pull request to fix this
