### ISSUE TITLE
Validate `io.whalebrew.*` labels

### ISSUE THREAD

**Issue by farkasmate** [whalebrew/whalebrew#125]
**Problem:** If a typo is made in the label name whalebrew is silently ignoring it. For example `io.whalebrew.config.volume` would not add volumes to the image.

**Goal:** Help whalebrew image developers to catch these bugs

**Example:**
- Using `whalebrew install` or similar (`validate`/`lint`) in build pipelines would surface warnings or errors
- Check for [these](https://github.com/whalebrew/whalebrew/blob/3906d374b3b83e8335cb5190c576137c2b850dda/packages/package.go#L92-L121) label names

**Benefits:**
- Better test coverage on whalebrew images

**Comment by tjamet** [comment]
Thanks for raising. Having a way to lint those labels is indeed a good idea. I am having a look at how to implement it.
