### ISSUE TITLE
whalebrew search does not list packages

### ISSUE THREAD

**Issue by ad-si** [whalebrew/whalebrew#132]
```
$ whalebrew search
Search for Whalebrew packages on Docker Hub. If no search term is provided, all packages are listed.

Usage:
  whalebrew search [TERM] [flags]

Flags:
  -h, --help   help for search
```

I provided no search term, but it showed the help and not all packages.

**Comment by tjamet** [comment]
Thanks for raising!
I will take a look at it

**Comment by tjamet** [comment]
The search help has been updated to disambiguate this behavior.
Closing this Issue.

If you think this should be the behaviour of search without argument, I am happy to have the discussion by re-opening this issue or in a new one
