### ISSUE TITLE
terraform outdated

### ISSUE THREAD

**Issue by captnswing** [whalebrew/whalebrew#135]
It seems the whalebrew/terraform docker image hasn't been updated in a while?

```
$ whalebrew install whalebrew/terraform
$ terraform -version
Terraform v0.12.23
```

compare this to

```
$ docker run --rm docker.io/hashicorp/terraform:latest -version
Terraform v0.15.3
on linux_amd64
```

**Comment by tjamet** [comment]
Hi!
indeed, there have not been any update there in a while
Those should probably be automated in a way

If you feel so, feel free to add the new version to the terraform repository: https://github.com/whalebrew/whalebrew-packages/blob/master/terraform/Dockerfile probably adding support for multiple tags, inspiring from awscli for instance https://github.com/whalebrew/whalebrew-packages/tree/master/awscli

Meanwhile I will have a look at how to automate those version bumps

**Comment by captnswing** [comment]
@tjamet the Dockerfile you link to already refers to the [terraform:latest](https://github.com/whalebrew/whalebrew-packages/blob/master/terraform/Dockerfile#L1) image. 

so re-triggering the build of this docker image should result in the latest and greatest terraform version

**Comment by memark** [comment]
Looks like that build still hasn't been triggered.

whalebrew provided version is still `Terraform v0.12.23`
while latest has now reached `Terraform v1.5.7`

**Comment by tjamet** [comment]
indeed, I did not have the expected time to automate the version bumps as envisioned.
Happy to receive contributions on [whalebrew-packages](https://github.com/whalebrew/whalebrew-packages)
Yet, I have just pushed a commit there to re-trigger the build

**Comment by tjamet** [comment]
I have just triggered a new build.
We need to make this process automatic though
