### ISSUE TITLE
Improve Install Path handling

### ISSUE THREAD

**Issue by jmlnik** [whalebrew/whalebrew#191]
**Currently**
Currently, the install path is hard-coded to /usr/local/bin and can only be overridden by setting the `WHALEBREW_INSTALL_PATH` environment variable.

**The Problem(s)**
Now that Homebrew installs to `/opt/homebrew/bin` on Apple Silicon, permissions of the `/usr/local/bin` folder need to be changed before Whalebrew can install packages (the folder belongs to root:wheel with perms 0755). That's not ideal.

Yes, setting the environment variable allows to install to a different directory but this fails when used with a Brewfile (brew bundle) as brew.sh filters out ENV vars by default (see Temporary Workaround)

**Suggested Solutions**

1. Adopt the same approach as Homebrew Core and install to /opt/whalebrew/bin on Apple Silicon
2. Implement an override solution that can be supported by `brew bundle`, eg. adding an install_path option to the config file

**Temporary Workaround**

A termporary workaround is to invoke `HOMEBREW_NO_ENV_FILTERING=1 brew bundle` and set `WHALEBREW_INSTALL_PATH=/my/install/path` but this is a bad solution given the warning that brew shouts:
> Warning: HOMEBREW_NO_ENV_FILTERING is undocumented, deprecated and will be removed in a future Homebrew release (because it breaks many things)!

**Comment by tjamet** [comment]
Hi!
Thanks for raising.
Indeed, there is room for improvement on how we can customize the various configuration options of whalebrew.

I doubt though that it is judicious to install whalebrew things in a homebrew folder. By default, we should keep the semantics.

What would be interesting is to understand what are the mechanisms `brew bundle` supports so we can find a long-term solution.

**Comment by jmlnik** [comment]
Hi @tjamet

I _did_ investigate thoroughly at the time and at the time, `brew bundle` really didn't offer much...

Note, I'm *not* suggesting whalebrew installs to a homebrew folder. I'm suggesting whalebrew adopts the same "pattern" but installs to its own folder `/opt/whalebrew/bin`. All that's necessary for this is to detect the architecture and switch the hard-coded path for Apple Silicon. I hope this makes sense!

```
// pseudo-code

if (architecture == Apple Silicon) {
  path = /opt/whalebrew/bin
} else {
  path = /usr/local/bin
}
```


The other solution is to add an install_path option to whalebrew's config file, allowing individual users to override the path as necessary.

```
// pseudo-code

if (config[install_path]) {
  path = config[install_path]
} else {
  path = /usr/local/bin
}
```

Or, better yet, add both!

I'm afraid I don't have time to write a PR until at least 2024...

**Comment by tjamet** [comment]
Hi @jmlnik!

The feature should have been implemented and available in this [build](https://github.com/whalebrew/whalebrew/actions/runs/6386051812).

It would be great to have your feedback about it.
What works and what not.

On MacOS, you will need to run `xattr -d com.apple.quarantine whalebrew-Darwin-$(uname -m)` to be able to remove the macOS download warnings and use it.
