### ISSUE TITLE
Was 0.4.0 re-tagged?

### ISSUE THREAD

**Issue by SMillerDev** [whalebrew/whalebrew#192]
When building Whalebrew in Homebrew on March 29th a revision was recorded but the current revision for the 0.4.0 release is different. If this was not done intentionally it could be a security issue. If it was done intentionally, the [git manual](https://git-scm.com/docs/git-tag#_on_re_tagging) says re-tagging is "the insane thing" to do.

See https://github.com/Homebrew/homebrew-core/pull/107227

**Comment by chenrui333** [comment]
Bump

**Comment by chenrui333** [comment]
cc @tjamet

**Comment by tjamet** [comment]
Hi!

I can't guarantee whether it was done or not, I don't find traces of it in the history.
Let's release a new version with the latest bumps to solve the checksums problem

**Comment by tjamet** [comment]
Taking a closer look, I can see that the commit [bdf94887abf0397341c1d241974eea790626ae7c](https://github.com/whalebrew/whalebrew/commit/bdf94887abf0397341c1d241974eea790626ae7c) to which the tag [0.4.0](https://github.com/whalebrew/whalebrew/releases/tag/0.4.0)  is pointing has effectively been signed by my personal GPG key, so did commit [1722002db3f1618f7af9d400343bf502d03b508f](https://github.com/whalebrew/whalebrew/commit/1722002db3f1618f7af9d400343bf502d03b508f).

<img width="1224" alt="image" src="https://github.com/whalebrew/whalebrew/assets/6061440/830dbb27-e07f-47af-bd3a-b66297fab3be">

This means that I was indeed the author of both commits.

This leads me to the conclusion that I may have made the mistake of re-tagging indeed.
