### ISSUE TITLE
Is the docker daemon running? (Oh yes it is!)

### ISSUE THREAD

**Issue by memark** [whalebrew/whalebrew#200]
Whalebrew seems to think my docker daemon is not running, but it most certainly is...

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/318504/197145488-6ca074f8-19af-4b39-906d-5a0fd2989473.png">

**Comment by osalbahr** [comment]
Are you able to `docker run --rm whalebrew/whalesay`?

**Comment by puls-com-leon-komarovsky** [comment]
This happens to me when the "Allow the default Docker socket to be used (requires password)" option is not set in docker configuration. 
In this case docker creates socket under `unix:///Users/$USER/.docker/run/docker.sock` and `whalebrew install ..` fails.
Already installed packages are useable.

The temporary solution might be to set up DOCKER_HOST environment variable to `unix:///Users/$USER/.docker/run/docker.sock` and install packages.

**Comment by tjamet** [comment]
Hi,

It could be some missing updates on the docker dependency.
I will update and release it to see whether it will fix the problem.

Otherwise I will evaluate reviewing how we inspect images so we don't depend on the docker daemon any longer

**Comment by tjamet** [comment]
[whalebrew 0.4.1](https://github.com/whalebrew/whalebrew/releases/tag/0.4.1) contains the updates of the docker libraries.
Would it help fix this problem for you?

**Comment by memark** [comment]
I have switched to podman since I created this issue. Using [this hack](https://github.com/whalebrew/whalebrew/issues/228#issuecomment-1588498644) however the 0.4.1 release works fine for me!

**Comment by puls-com-leon-komarovsky** [comment]
@tjamet still having the same issue with 0.4.1
```
$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

$ brew info whalebrew
==> whalebrew: stable 0.4.1 (bottled), HEAD
Homebrew, but with Docker images
https://github.com/whalebrew/whalebrew
/Users/www/.brew/Cellar/whalebrew/0.4.1 (9 files, 12.6MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-09-21 at 11:53:15
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/w/whalebrew.rb
License: Apache-2.0
==> Dependencies
Build: go ✘
==> Options
--HEAD
	Install HEAD version
==> Caveats
Bash completion has been installed to:
  /Users/www/.brew/etc/bash_completion.d
==> Analytics
install: 64 (30 days), 171 (90 days), 294 (365 days)
install-on-request: 64 (30 days), 171 (90 days), 294 (365 days)
build-error: 0 (30 days)

$ whalebrew install whalebrew/jq
failed to inspect docker image: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by memark** [comment]
@puls-com-leon-komarovsky That might be because [the reported version is not correct](https://github.com/whalebrew/whalebrew/issues/233). Try running `whalebrew version` to verify.

**Comment by tjamet** [comment]
Thanks for your feedback!

In the context of #228 I have refactored the way we inspect image to call `docker` instead of using the docker socket.

I am still testing and developing it, but it would be great to get your feedback whether it improves in this area or not.

Here is the latest build that has the executable for all platforms attached as output:
https://github.com/whalebrew/whalebrew/actions/runs/6264518160

On MacOS, you will need to run `xattr -d com.apple.quarantine whalebrew-Darwin-$(uname -m)`  to be able to remove the macOS download warnings and use it.

**Comment by puls-com-leon-komarovsky** [comment]
I can confirm that the build above works for me

**Comment by tjamet** [comment]
great news!
Thanks!
