### ISSUE TITLE
podman support

### ISSUE THREAD

**Issue by abitrolly** [whalebrew/whalebrew#228]
`whalebrew` doesn't seem to support `podman`.

```
$ whalebrew install ghcr.io/mlflow/mlflow:v2.3.2
failed to inspect docker image: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by timescam** [comment]
I also have the same issue, what I did is soft link podman as docker
```bash
doas ln -s $(which podman) /opt/homebrew/bin/docker
```
swap `/opt/homebrew/bin` to `/usr/local/bin` if you're on x86

**Comment by tjamet** [comment]
Hi!

Indeed, it uses the docker library to inspect the images.
I will take a look how to improve this part.

**Comment by memark** [comment]
I'm also on padman nowadays.
@timescam's hack works for me. But it would be nice to be able to just set an env var or smth that whalebrew would respect.

**Comment by tjamet** [comment]
This [build](https://github.com/whalebrew/whalebrew/actions/runs/6264518160) contains the dev version of podman support.
It would be great to have your feedback about it.
What works and what not.


On MacOS, you will need to run `xattr -d com.apple.quarantine whalebrew-Darwin-$(uname -m)` to be able to remove the macOS download warnings and use it.

**Comment by memark** [comment]
For me this is not working:

* create a temp dir
* download the arm64 build to there
* removing quarantine and set +x
* add current dir to PATH
* rename downloaded file to `whalebrew`

```
❯ whalebrew version
Whalebrew 0.4.1-1-gef526bd

❯ whalesay
zsh: command not found: whalesay

❯ whalebrew install whalebrew/whalesay
🐳  Installed whalebrew/whalesay to /usr/local/bin/whalesay

❯ whalesay running with podman!
WARNING: image platform (linux/amd64) does not match the expected platform (linux/arm64)
Error: statfs /var/folders/pz/cl5g3tqx5yd20d7ylmx629x00000gn/T/tmp.HB4dvGlzsO: no such file or directory
```

other info

``````

**Comment by memark** [comment]
Do note that running the container directly with podman actually works

```
❯ podman run --rm whalebrew/whalesay running with podman!
WARNING: image platform (linux/amd64) does not match the expected platform (linux/arm64)
 ______________________
< running with podman! >
 ----------------------
    \
     \
      \
                    ##         .
              ## ## ##        ==
           ## ## ## ## ##    ===
       /"""""""""""""""""\___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
       \______ o           __/
         \    \         __/
          \____\_______/
```

**Comment by tjamet** [comment]
Thanks for your input @memark 
I think the problem you are facing is that whalebrew mounts the working directory to the container, as described in ["How it works"](https://github.com/whalebrew/whalebrew#how-it-works)

Because of the way podman and docker works on mac (i.e running in a vm) they don't have access to all folders on the machine.

I think, using the same script and replacing `whalesay running with podman!` by `podman run --rm -v $PWD:/workdir whalebrew/whalesay running with podman!` you will have the same problem.
Would it be worth trying?

Here is the result on my machine (x86):

```
❯ mktemp -d
/var/folders/0d/rvmll2615l19k0sy4g734kcm0000gn/T/tmp.r0XgqFvd

❯ podman run --rm -v /var/folders/0d/rvmll2615l19k0sy4g734kcm0000gn/T/tmp.r0XgqFvd:/workdir --rm whalebrew/whalesay running with podman!
Error: statfs /var/folders/0d/rvmll2615l19k0sy4g734kcm0000gn/T/tmp.r0XgqFvd: no such file or directory
```

In case you would try the same thing with whalebrew 4.1.0, not having this support, you would get:

```
❯ whalebrew version
Whalebrew 0.4.1

❯ whalebrew install whalebrew/whalesay
failed to inspect docker image: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

❯ whalesay
exec: "docker": executable file not found in $PATH
```

I don't have enough knowledge on podman to tell you whether it is achievable with podman or not. With a super quick search I find this issue talking about $HOME but not sure it talks about other volumes
https://github.com/containers/podman/issues/13944

**Comment by memark** [comment]
@tjamet Actually your first podman example works fine on my machine:

```
❯ mktemp -d
/var/folders/pz/cl5g3tqx5yd20d7ylmx629x00000gn/T/tmp.zHTSCXYx8p

❯ podman run --rm -v /var/folders/pz/cl5g3tqx5yd20d7ylmx629x00000gn/T/tmp.zHTSCXYx8p:/workdir whalebrew/whalesay running with podman!
WARNING: image platform (linux/amd64) does not match the expected platform (linux/arm64)
 ______________________
< running with podman! >
 ----------------------
    \
     \
      \
                    ##         .
              ## ## ##        ==
           ## ## ## ## ##    ===
       /"""""""""""""""""\___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
       \______ o           __/
         \    \         __/
          \____\_______/

```

(TBH I don't know much about podman inner workings. I just switched to it due to the changed made to the Docker Desktop licensing model.)

**Comment by tjamet** [comment]
This is interesting.

Whalebrew runs this exact command (assuming podman is in `/usr/local/bin/podman`, the whalesay file was not changed from the standard installation, the current directory on the host OS is `/var/folders/0d/rvmll2615l19k0sy4g734kcm0000gn/T/tmp.2w5oppGh` and the current user ID on the local machine is `501`.):

```
❯ /usr/local/bin/podman "run" "--interactive" "--rm" "--workdir" "/workdir" "--init" "--tty" "-v" "/var/folders/0d/rvmll2615l19k0sy4g734kcm0000gn/T/tmp.2w5oppGh:/workdir" "-u" "501:20" "whalebrew/whalesay" "running" "with" "podman"
```

Would this command work for you?

**Comment by memark** [comment]
```
❯ type podman
podman is /opt/homebrew/bin/podman

❯ mktemp -d
/var/folders/pz/cl5g3tqx5yd20d7ylmx629x00000gn/T/tmp.lgJdykhujq

❯ cd /var/folders/pz/cl5g3tqx5yd20d7ylmx629x00000gn/T/tmp.lgJdykhujq

❯ /opt/homebrew/bin/podman "run" "--interactive" "--rm" "--workdir" "/workdir" "--init" "--tty" "-v" "/var/folders/pz/cl5g3tqx5yd20d7ylmx629x00000gn/T/tmp.lgJdykhujq:/workdir" "-u" "501:20" "whalebrew/whalesay" "running" "with" "podman"
WARNING: image platform (linux/amd64) does not match the expected platform (linux/arm64)
 _____________________
< running with podman >
 ---------------------
    \
     \
      \
                    ##         .
              ## ## ##        ==
           ## ## ## ## ##    ===
       /"""""""""""""""""\___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
       \______ o           __/
         \    \         __/
          \____\_______/
```

**Comment by tjamet** [comment]
I have just tried again with the command from this [build](https://github.com/whalebrew/whalebrew/actions/runs/6357368767), on a mac with m2, the commands above, those worked for me, even running in a temporary directory.

podman client: 4.7.0
podman server: 4.6.2

Do you still observe the behaviour with whalebrew?

**Comment by memark** [comment]
With that build it works for me to (install and) run whalesay in the normal way. Good work!
