### ISSUE TITLE
Homebrew version of whalebrew is incorrect

### ISSUE THREAD

**Issue by memark** [whalebrew/whalebrew#233]
The homebrew version of whalebrew is lagging behind it seems, even though the formula seems to think it's up to date:

```
❯ brew info whalebrew
==> whalebrew: stable 0.4.0 (bottled), HEAD
Homebrew, but with Docker images
https://github.com/whalebrew/whalebrew
/opt/homebrew/Cellar/whalebrew/0.4.0 (9 files, 12.3MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-09-21 at 07:33:38
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/w/whalebrew.rb
License: Apache-2.0
==> Dependencies
Build: go ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Analytics
install: 57 (30 days), 164 (90 days), 287 (365 days)
install-on-request: 57 (30 days), 164 (90 days), 287 (365 days)
build-error: 0 (30 days)

❯ whalebrew version
Whalebrew 0.3.0

❯ type whalebrew
whalebrew is /opt/homebrew/bin/whalebrew
```

Notice `0.4.0` vs. `0.3.0`

**Comment by tjamet** [comment]
Thank you for raising.
Indeed, this seems to be restricted to the homebrew version.
The version provided in the [release](https://github.com/whalebrew/whalebrew/releases/tag/0.4.1) has the relevant version number:
<img width="561" alt="image" src="https://github.com/whalebrew/whalebrew/assets/6061440/a0a615f1-63e0-435f-a747-1d0d9041c0cd">

I will check if I can do anything for this.

**Comment by tjamet** [comment]
As you may have noticed, I have opened the PR on homebrew to fix this

**Comment by tjamet** [comment]
The homebrew PR has been merged.
closing this issue

**Comment by memark** [comment]
Thanks, working now as expected.
