### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by shpoont** [whalebrew/whalebrew#282]
Hi team,

I have noticed that there has been reduced activity on the Whalebrew repository recently, and I wanted to inquire about the current status of the project. Is Whalebrew still being actively maintained and developed? I find this tool incredibly useful and hope that the reduced activity is only temporary. Thank you for all your hard work on this project ❤️

**Comment by tjamet** [comment]
Hi!

Thank you for reaching. 
It is true that I have been a bit disconnected from GitHub for personal purposes lately.

I am doing my best to tackle the required updates (PRs and issues).

Given the project maturity, I don't expect much work on the core itself.

Ideally, reducing the effort of package maintenance would be great.

**Comment by shpoont** [comment]
Hi @tjamet,

I’m glad to hear that the project is still active. I appreciate your efforts in maintaining Whalebrew despite the challenges. There are a few unmerged PRs that should solve the issues that are currently making Whalebrew completely unusable. It would be great if these could be reviewed and merged. Thank you again for your hard work!

**Comment by tjamet** [comment]
I have reviewed and merged most of the PRs. I think those will indeed help.
I plan to release shortly. Meanwhile, don't hesitate to test those changes using `go install github.com/whalebrew/whalebrew@master`

**Comment by shpoont** [comment]
@tjamet I installed and tested some basic functionality, it looks ok so far

**Comment by tjamet** [comment]
Great!

Thank you for your feedback.

I just released 0.5.0 to make it official.

I will hence close this issue
