### ISSUE TITLE
Make Whalebrew a Docker image

### ISSUE THREAD

**Issue by bfirsh** [whalebrew/whalebrew#32]
It'd be neat if we could ship Whalebrew as a Docker image, and make the binary a shell script which runs `docker run whalebrew/whalebrew ...`.

A number of barriers to this:

* It is an extra level of indirection, making it slower and less reliable. In particular, running any command will require running at least two containers. Maybe there are some tricks here, e.g. Whalebrew ships in a container, except `whalebrew run` which is handled by a shell script on the host that is installed/updated by the container.
* We need to pass arbitrary envvars, ports, and volumes to containers that are run that are defined by the package.

**Comment by tjamet** [comment]
Just throwing the idea

Could we have a permanently running container, and then, we just have to `docker exec` into it?
This would solve the first problem with slowness.
This means we also need to be careful about forwarding properly signals and forwarding environment variables.

This approach does not solve use-case of #36 that could be worth solving at the same time?

To do so, we could also run the above container as a `whalebrew daemon` exposing, for instance, a unix socket. This container would expose a volume containing the commands, the whalebrew in whalebrew `client` and the communication socket. Commands would then be mounted `--volumes-from whalebrew`
this could end up as `docker run --name whalebrew -d whalebrew/whalebrew whalebrew daemon`
and whalebrew to call, for example, `docker container run --volumes-from=whalebrew whalebrew/awscli`

The problem with this approach, although it is a bit complex, is that we need to provide a server to expose the whalebrew run with all it implies (forward stdin/out/err, forward signals, ...), causing the second level of indirection with defects mentioned above
