### ISSUE TITLE
Create a Homebrew formula

### ISSUE THREAD

**Issue by bfirsh** [whalebrew/whalebrew#33]
$ brew install whalebrew

https://twitter.com/teabass/status/824682166361751552

**Comment by kballard** [comment]
You don't even need to actually get a formula in the Homebrew repository. You can just put your formula.rb in this repository and tell people to use `brew install --HEAD https://raw.githubusercontent.com/bfirsh/whalebrew/master/path/to/whalebrew.rb`. That will then install it with Homebrew, and users can use `brew upgrade whalebrew` and it'll pull the latest version of the formula automatically.

**Comment by themalkolm** [comment]
Hacked one for myself https://github.com/themalkolm/homebrew-brew/blob/master/Formula/whalebrew.rb

```
brew tap themalkolm/brew
brew install whalebrew
```

**Comment by themalkolm** [comment]
I can automate formula generation & contribute if people want this.

**Comment by bfirsh** [comment]
@themalkolm yes please :D

**Comment by 0xdevalias** [comment]
I wonder if this package would be 'nicer' if it just installed the binaries from the release page instead of requiring to build it locally?

It also seems to be a bit dated.

**Comment by themalkolm** [comment]
I updated to use binaries instead https://github.com/themalkolm/homebrew-brew/blob/master/Formula/whalebrew.rb

**Comment by superbrothers** [comment]
@tjamet @bfirsh I also wanted to install whalebrew with homebrew, so I created homebrew formula (https://github.com/superbrothers/homebrew-whalebrew) for whalebrew.
If possible, I'd like to move the repository under the whalebrew organization. WDYT? (If you want, I will continue to maintain the formula ;)

**Comment by tjamet** [comment]
@superbrothers It looks like a bit of inception but I can understand the need for it
I would indeed consider the idea of transferring your repo to the org
Not sure about a contribution to https://github.com/Homebrew/homebrew-core/tree/master/Formula could be an idea to get `brew install whalebrew` by default?

**Comment by superbrothers** [comment]
@tjamet All right. I'll try to add formula to homebrew-core.

**Comment by superbrothers** [comment]
@tjamet When will you make the next release of whalebrew? I'm going to make a PR of homebrew-core after the next release. (I want to include the change of using Go Modules to the PR.)

**Comment by tjamet** [comment]
We can plan a release for next month I think we have few things we can release

**Comment by tjamet** [comment]
Hey @superbrothers Sorry it took me longer than expected to release, but [0.2.2](https://github.com/whalebrew/whalebrew/releases/tag/0.2.2) is now released

**Comment by superbrothers** [comment]
Now, we can install whalebrew via Homebrew :tada:

```
$ brew install whalebrew
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/whalebrew-0.2.2.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/47/4788986bffaaad6defb524a5e2f8d7093f77fbd0004fa0f4cf52ebcb4134e240?__gda__=exp=1563154156~hmac=dbb85ce33d64392e0efb8fdcb591e5539032e831785c7d566986da4e4f13d514&response-content-disposition=attachment%3Bfilename%3D%22whalebrew-0.2
######################################################################## 100.0%
==> Pouring whalebrew-0.2.2.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/whalebrew/0.2.2: 6 files, 15.1MB
```

**Comment by bfirsh** [comment]
@superbrothers NICE! Thank you so much!

This would make a neat addition to the installation instructions in the readme. "Upgrade from Homebrew to Whalebrew" ;)

@tjamet A little thing -- I noticed the version number in the readme installation instructions is out of date. I wonder if that can be automated somehow...

**Comment by tjamet** [comment]
@bfirsh Indeed, created #87 :)
