### ISSUE TITLE
Missing files creates directories

### ISSUE THREAD

**Issue by snodnipper** [whalebrew/whalebrew#38]
The default behaviour of Docker is to create directories of locations that do not exist.

For example, I created a [git package example][1] that initially mounted locations like so:

`LABEL io.whalebrew.config.volumes '["~/.gitconfig:/root/.gitconfig", "~/.ssh:/root/.ssh"]'`

Consequently, when ~/.gitconfig not exist then a directory named .gitconfig is created.  It is also [documented][2] that inode changes produce errors such as “[d]evice or resource busy”.

Example error:
```terminal
ubuntu@ip-172-32-43-16:~/whalebrew$ git config --global user.email “joe@bloggs.com"
error: could not write config file /root/.gitconfig: Resource busy
```

The above was resolved by using:

`LABEL io.whalebrew.config.volumes '["~/:/root/"]'`

Clearly, the above gives git access to the entire home directory.

The above leads me to question whether it would be useful for whalebrew to mount a surrogate parent directory (e.g. /tmp/random/) when files (e.g. .gitconfig) are encountered (copying files, if necessary, into the surrogate).  This restricts access to the host filesystem and gives the opportunity for the command to create default file(s), which I’d guess whalebrew could copy back.

[1]: https://github.com/snodnipper/whalebrew-git
[2]: https://docs.docker.com/engine/tutorials/dockervolumes/#/mount-a-host-file-as-a-data-volume

@jskeates

**Comment by tjamet** [comment]
Hi, thanks for reporting, indeed, this is annoying, just pushed a branch to solve this issue.
By default in this branch, Whalebrew will refuse to mount volumes that does not exist.
There is a customisable option to either:
- skip mounting non-existing volumes and go on with the execution
- go on mounting volumes and get docker to create the non-existing folder
