### ISSUE TITLE
`whalebrew search` on macOS (whalebrew installed via homebrew) returns nothing

### ISSUE THREAD

**Issue by duckpuppy** [whalebrew/whalebrew#88]
I've installed whalebrew on macOS via homebrew, and search is not working at all.  `whalebrew search` returns nothing, either with or without search parameters.

Whalebrew 0.2.3
Docker version 18.09.2, build 6247962
macOS 10.14.5

**Comment by duckpuppy** [comment]
OK, I'm going to remove the install issue, because I'm dumb and didn't read the instructions closely enough.  However, `whalebrew search` doesn't work at all still.

**Comment by tjamet** [comment]
Thanks for reporting, will have a look at it soon

**Comment by mrmachine** [comment]
I'm seeing the same thing. On macOS 10.15.4, after installing Docker and Whalebrew via Homebrew, `whalebrew search` with or without arguments returns no errors or any output at all, and a successful exit code.

**Comment by bjfr** [comment]
Yes, it is broken for me too, MacOS 10.15.5. Not possible to search, with or without parameters...
