### ISSUE TITLE
Document how to add custom volumes, ports, etc

### ISSUE THREAD

**Issue by nithin-bose** [whalebrew/whalebrew#9]
There are some applications when dockerized need extra params like env variables or volumes to run. It would be cool to have an easy way to change the exec command generated by whale brew.

I was thinking about maybe a config to specify the exec command to be used but then the current workflow is so simple that I would say its almost beautiful.

Another way might be to have more options in the generated YAML file. Why didnt you just generate the docker compose file? 

Trying to start a discussion. Again thanks a lot for the wonderful project.

**Comment by bfirsh** [comment]
How about this? ;)

https://github.com/bfirsh/whalebrew#configuration-1

**Comment by nithin-bose** [comment]
@bfirsh Not exactly. 
My use case is about changing volume and port config at run time. Labels would only let me do that when the image is created. This means that only the author of the image can make these changes and not the guy who installs the image.

I went through the code and interestingly, you are doing what I want already. Since the configuration LABELs are used to generate the volumes and ports section in the package file which is used to run the container, me as a user of whalebrew can edit the generated package file to change these configurations after installing.

I tested this with whalebrew/irssi and it works. I could change the path of the mounted .irssi folder by editing the package file (/usr/local/bin/irssi) I am pretty sure the same would work for ports as well. 

An interesting side effect of this would be that I could use any any docker image out there. ``whalebrew redis``, meddle with the package file and I get redis. Cool!! 

It would be great if you can update the docs to reflect the same. Maybe this could be made a cli option later on, for convenience.

**Comment by nithin-bose** [comment]
By the way, the redis example i mentioned also works. 
Steps:
1. whalebrew redis
2. Edit the generated ``/usr/local/bin/redis`` file to add the following:
```
ports:
  - "6379:6379"
```
3. use redis

Awesome!!

**Comment by bfirsh** [comment]
Okay, yeah good point. We should document how users can change the package config. :+1:

**Comment by tjamet** [comment]
I am understanding that the feature has been implemented with the `edit` command merged with a488187, #39 hence, I am closing this issue
Please feel free to re-open if you see anything that can be improved
